### ISSUE TITLE
[DISCUSSION] Just some stuff that annoys me

### ISSUE THREAD

**Issue by JasonTheKitten** [nothjarnan/axiom#38]
I am about to go on a long rant. If nothing else, look at this bullet point list.
Much of what I say is geared towards increasing code maintainability now that we are open-source, and decreasing used disk space
- Use sensible code, not copy/paste
- If you copy/pasted something many times, then while the optimization may not be prevalent, there likely is one
- Just don't copy/paste. It uses too much disk space and decreases code maintainabilty
- Be sensible. You can almost always optimize long code, even if it is just a list containing data for a boot animation. Especially then
- Hotfixes are good, people PR them for a reason
- Do not pollute global namespace (and there is almost never a reason to use os.loadAPI on your own APIs)
- Group stuff, it makes life easier
- Use [camel case](https://en.wikipedia.org/wiki/Camel_case). It is a standard among many developers
- Avoid long inter-nested functions
- Clean up your code. You have a lot of unused variables and commented code, and I bet some of your code does little more than nothing. Not sure if it what I think it is, but I found [this](https://github.com/davidm/lua-inspect).
- Take advantage of CC's APIs if you are going to do the exact same thing they do. If you are going to look for a peripheral and you do not know where it is, use peripheral.find, not peripheral.wrap

<br><br><br><br><br><br>
I am posting this b/c of [your latest commit](https://github.com/nothjarnan/axiom/commit/e9ac30c3e33c6350462de15ac606787986fdebb5). 

Many of Axiom's features use _way_ too much disk space, even though it is not needed. The alternatives will make life easier, use less disk space, make the code more maintainable, and make the user's experience more enjoyable.

Instead of, for example, `loadinganim={...}` , which takes 10 lines of code, we can settle for this instead:
```
local loadinganim = {"o":rep(7)}
for i = 1, 7 do
  table.insert(loadinganim, "o":rep(i-1).."O".."o":rep(7-i))
end
```
This is 4/7 the code, almost 1/2

I don't even know what happened [here](https://github.com/nothjarnan/axiom/blob/e9ac30c3e33c6350462de15ac606787986fdebb5/Axiom/sys.lua#L818). Once the color is black, it's black. No need to make it black again.

The [below](https://github.com/nothjarnan/axiom/blob/e9ac30c3e33c6350462de15ac606787986fdebb5/Axiom/sys.lua#L39) is not only excess code, but the alternative code is more useful, as it let's us use any monitor:
```
for k,v in ipairs(sides) do
  if peripheral.isPresent(v) then
    if peripheral.getType(v) == "speaker" then
      speakerSide = v
      speakerPresent = true
      speaker = peripheral.wrap(v)
      speaker.playNote("harp",1, 1)
      break
    end
    if peripheral.getType(v) == "monitor" then
      monitor = peripheral.wrap(v)
    end
  end
end
```

Instead, we can just say
```
monitor = peripheral.find("monitor")
speaker = peripheral.find("speaker")
if speaker then
  speaker.playNote("harp", 1,  1)
end
```
I'm sure you can see how much less code we use.
Yes, we don't have speakerSide, but we get the advantage of being able to use any monitor
And the speakerPresent variable was never necessary: we just say
`if speaker then`, or `not not speaker`

Another thing is this:
<details closed> 
<summary>Code</summary>
<code lua>
  term.setBackgroundColor(bgCol)
  term.setTextColor(colors.white)
  edge.cprint(productName,10)
  sleep(0.1)
  term.setBackgroundColor(bgCol)
  term.setTextColor(colors.lightGray)
  edge.cprint(productName,10)
  sleep(0.1)
  term.setBackgroundColor(bgCol)
  term.setTextColor(colors.gray)
  edge.cprint(productName,10)
  sleep(0.1)
  term.setBackgroundColor(bgCol)
  term.setTextColor(colors.black)<br>
  edge.cprint(productName,10)<br>
  sleep(2)<br>
  term.setBackgroundColor(bgCol)<br>
  term.setTextColor(colors.black)<br>
  edge.cprint(productName,10)<br>
  sleep(0.1)<br>
  term.setBackgroundColor(bgCol)<br>
  term.setTextColor(colors.gray)<br>
  edge.cprint(productName,10)<br>
  sleep(0.1)<br>
  term.setBackgroundColor(bgCol)<br>
  term.setTextColor(colors.lightGray)<br>
  edge.cprint(productName,10)<br>
  sleep(0.1)<br>
  term.setBackgroundColor(bgCol)<br>
  term.setTextColor(colors.white)<br>
  edge.cprint(productName,10)<br>
</code>
 </details><br>

Surely we could just do this:
```
local cols = {colors.white, colors.lightGray, colors.gray, colors.black}
local sz = #cols
for i=0, sz-1 do
  table.insert(cols, cols[sz-i])
end
for k, v in pairs(sz) do
  term.setBackgroundColor(bgCol)
  term.setTextColor(v)
  edge.cprint(productName, 10)
  sleep(((k==sz) and 2) or .1)
end
```
Not only that, this automates our coding a little bit. 4 of the lines in the code I gave actually are not needed, but that will make life easier for you. The goal is not to copy, paste, copy, paste the same snippets of code over and over: it is a waste of disk space and makes fixes harder

In addition, it may be beneficial to perform a code cleanup every once in a while. This will reduce used disk space and also make code maintenance easier.

Code cleanup includes removing [unused namespaces](https://github.com/nothjarnan/axiom/blob/e9ac30c3e33c6350462de15ac606787986fdebb5/Axiom/sys.lua#L124), [commented code](https://github.com/nothjarnan/axiom/blob/e9ac30c3e33c6350462de15ac606787986fdebb5/Axiom/sys.lua#L403), and [unused code](https://github.com/nothjarnan/axiom/blob/e9ac30c3e33c6350462de15ac606787986fdebb5/Axiom/sys.lua#L305).

Another thing is that you are not hotfixxing [what needs hotfixed](https://github.com/nothjarnan/axiom/issues/35), even though the steps to reproduced are easy to follow, the error message is easily obtainable (And you make me laugh, ["I need the stacktrace, please."](https://github.com/nothjarnan/axiom/issues/35#issuecomment-393540190)), and a [hotfix](https://github.com/nothjarnan/axiom/pull/36) (which cannot break anything because it is only executed where the code occurs) is readily available

Not all optimizations are easy to figure out, but they are there
[This](https://github.com/nothjarnan/axiom/blob/e9ac30c3e33c6350462de15ac606787986fdebb5/Axiom/sys.lua#L167) simplifies to this:
```
local printwarn, printout, printerr
do
 local function x(col, t)
  return function(text)
  if edge then
    if edge.hasScreen() then
      edge.printout(text)
    end
  end
  term.setTextColor(colors.gray)
  write("[")
  term.setTextColor(col)
  write(t)
  term.setTextColor(colors.gray)
  write("]")
  term.setTextColor(colors.white)
  print(" "..text)
  end
 end
printwarn, printout, printerr = x(colors.orange, "WARN"), x(colors.red, "ERROR"), x(colors.gray, "INFO")
end
```

A few last things:

- I generally frown at using the global namespace, especially with 1.8pr0 released. loadfile, load, and setfenv all go a long way, as opposed to _G and os.loadAPI
- Group functions and vars, based off of both scope and general type/purpose. Put the main code at ther bottom
- Short interested functions are fine. Longer ones, not so much
- Use camel case. That is one of the first things sites like Khan Academy teach you

**Comment by nothjarnan** [comment]
Mind you, I've got an unpublished commit that is a step towards all this stuff. I'm working my ass off to clean up this code while working half time.  The rest goes to this.

Furthermore, if you're so interested in how the scripts look, why not help clean them up? It'd be greatly appreciated.

**Comment by JasonTheKitten** [comment]
> Mind you, I've got an unpublished commit that is a step towards all this stuff. I'm working my ass off to clean up this code while working half time. The rest goes to this.

I didn't know, and I didn't realize you got a job (I tried to get one, but there were only two I was old enough for). Sorry.

> Furthermore, if you're so interested in how the scripts look, why not help clean them up? It'd be greatly appreciated.

[If you've forgotten](https://github.com/nothjarnan/axiom/pull/20)

Yes, I'll help clean up, but it may not be instant

**Comment by nothjarnan** [comment]
> If you've forgotten

Ah. If you still have the code, feel free to reupload it and PR it.

**Comment by JasonTheKitten** [comment]
I don't think I do, but I am going to try a complete restructuring of the code.

While I am restructuring, I'm going to make it so that the apps don't have to bother redrawing the title bar, as they should not have to carry that burden, and some of the logs and just the slightest bit of functionality may change. The code will look dramatically different, but the OS won't

In addition, printwarn, printerr, and printlog will all be merged into a single function, assuming you do not mind. The output will be the same.

This will be the new function: `log(msg, severity)`

The APIs will be rebased in such a way that they will work with both `os.loadAPI()` and `loadfile()()`, and edge will be greatly simplified

Would you be interested if we divided the kernel into more files. This would make it more maintainable

**Comment by nothjarnan** [comment]
Splitting the OS into more files sounds like a pretty OK idea, I'm guessing having the desktop rendering in one file, login screen logic in one file, then having one kernel file where it all comes together?

**Comment by JasonTheKitten** [comment]
Yea, just about

As for the safeboot stuff, should that be in separate files?

**Comment by nothjarnan** [comment]
Nah, safeboot should be in the kernel as it only really ever uses it after a fatal error/crash, or is supposed to anyway.

**Comment by nothjarnan** [comment]
> I don't even know what happened here. Once the color is black, it's black. No need to make it black again.

This was because of a bug in cc 1.75, where you'd switch background color without it applying. The solution was to simply "spam switch" until it eventually caught the change. This was basically the hackiest solution.

**Comment by JasonTheKitten** [comment]
Here is what I have so far on cleanup:
https://github.com/JasonTheKitten/axiom/commit/b50e2c7040d6195554200bc6295773956d534258?diff=unified
