### ISSUE TITLE
Settings "Delete user" is broken

### ISSUE THREAD

**Issue by JasonTheKitten** [nothjarnan/axiom#41]
There is no "by" field of users[k] on around line 730 or so

**Comment by nothjarnan** [comment]
I'll look into it.

**Comment by JasonTheKitten** [comment]
Anything yet on this issue?
Also, over PM you said I could do whatever with AxiomUI, do you mind if I write a version on top of my  framework (Ribbon)?

**Comment by nothjarnan** [comment]
Sure.

**Comment by nothjarnan** [comment]
Delete user works now. Not entirely sure why I put the issue off for almost two years. ¯\_(ツ)_/¯
