### ISSUE TITLE
Infinite Boot Crash after startup edit

### ISSUE THREAD

**Issue by jojomoore2007** [nothjarnan/axiom#42]
# This is an absolute MUST-FIX bug!
"sys.lua:474: attempt to index ? (a nil value)"

If you were one of the few people who thought it would be a good idea to make a reinstaller for when Axiom's sys.lua file was missing or corrupted, you know of this bug. If you even edit a single character of the "startup" boot file, used in /rom/ to start CraftOS, and in Axiom to make sure the sys.lua file exists, the following happens at boot:

1. Axiom UI fade black-to-white screen
1. "oooooooo" loading screen (usually shown when system files are missing or corrupted)
1. Split-second login screen
1. The following crash: 
```
+-------------------------+
+-------------------------+
|Axiom UI has crashed. Err|
|or: sys.lua:474: attemp  |
|t to index ? (a nil val  |
|ue)                      |
| Reboot?                 |
|                         |
|   [ Yes  ]   [  No  ]   |
+-------------------------+
```

And the thing is, trying to terminate it just shuts down the computer, meaning it's impossible to fix without editing the filesystem via the level.dat file for the level.

Please fix this! Also, trying to close the file explorer doesn't work.
Thanks!

-Joey (TheQWERTYCoder)

**Comment by nothjarnan** [comment]
I'll have a look into this. Thanks for pointing this bug out!

**Comment by nothjarnan** [comment]
I have had a very brief look, from what I can tell, this has to do with the updated login screen. 
The quick and dirty fix is to go into Settioand restore legacy login. Or `edit Axiom/settings.bak` and change `restore_legacy_login` to `true`. Then reboot.

**Comment by jojomoore2007** [comment]
Tried the legacy login fix, but can't seem to login anymore.

**Comment by jojomoore2007** [comment]
I looked in the "settings.bak" file, and found that my user didn't have an entry like Guest and KERNEL and temp. Reinstall fixes the issue tho.

So it turns out there wasn't a problem with the system, but rather the users. :) Thanks for the support!

**Comment by nothjarnan** [comment]
The user system not creating a new user upon first time setup is a known issue with Axiom. I think it's fixed in the experimental branch, though. Cheers!

EDIT: Keeping this issue open until it's known to be fixed.

**Comment by jojomoore2007** [comment]
OK!
Also, I might try to create a fixed master branch and do a pull request to fix this. Thanks!

**Comment by nothjarnan** [comment]
You are free to do so. Enjoy

**Comment by nothjarnan** [comment]
Any updates on the fix?
