### ISSUE TITLE
When are you going to update this to 1.8?

### ISSUE THREAD

**Issue by Kashotex** [nothjarnan/axiom#45]

**Comment by nothjarnan** [comment]
I'm currently in the process of building a better OS, and Axiom will most likely see some of the improvements from the new OS. 

Are there any particular things that you're currently having issues with?

**Comment by Kashotex** [comment]
whenever i actually load in, it says paintutils.lua is missing or something like that

**Comment by Kashotex** [comment]
![Capture](https://user-images.githubusercontent.com/55033374/71592736-66538c80-2aff-11ea-8ecb-604192be8efc.PNG)

**Comment by nothjarnan** [comment]
That should not be happening. What version of CC are you on, and are you running any particular modpack?

**Comment by Kashotex** [comment]
I am running version 1.8 and i am using my own modpack https://bit.ly/2Q36DTr

**Comment by nothjarnan** [comment]
Alright, I'll have a look ingame.

**Comment by Kashotex** [comment]
any updates?

**Comment by nothjarnan** [comment]
Not yet

**Comment by nothjarnan** [comment]
Update. It appears that the background functionality is broken. The fastest remedy for this is to edit Axiom/settings.bak, go to your user data and set background to "black". 
Like this:
```lua
test = {
      allow_apis = false,
      superuser = true,
      lastlogin = "Just now",
      allow_downloads = true,
      background = "black",
      displayName = "test",
      fexplore_startdir = "/home/",
      system_skipsys_scan = false,
      password = "5aeda02c4e69ea884358a897f8359366628136af821491adb1cc806a0b1061d4",
      system_skip_error = false,
    }

**Comment by nothjarnan** [comment]
It'll have to do until I've figured out a fix, it's got something to do with the version of CC you're running.

**Comment by Kashotex** [comment]
Alright, all good

**Comment by nothjarnan** [comment]
Best way to do this is to go through the first time setup, then shut the computer off during bootup, then you put the computer into a disk drive of a non-advanced computer, then run `edit Axiom/settings.bak`

**Comment by LDDestroier** [comment]
I've made a commit to master that might fix that strange paintutils bug. I'll have to see if it doesn't crash tomorrow morning

**Comment by nothjarnan** [comment]
Commit 78571b7a09b3714e330319b0e0f8dbf4921be682 broke Edge.
![image](https://user-images.githubusercontent.com/15698707/71618688-a88cd480-2bb8-11ea-98b5-4f64ad138f64.png)

**Comment by nothjarnan** [comment]
bbd7691fb0cd3ec99a2f01418a895090d182a930 fixes this issue on master. Will update to experimental later today.

**Comment by Kashotex** [comment]
Thanks man

**Comment by nothjarnan** [comment]
np.

**Comment by nothjarnan** [comment]
Hotfix has been applied to master. It should work now.
