### ISSUE TITLE
Make updater fetch files from repo instead of reporting failed update

### ISSUE THREAD

**Issue by nothjarnan** [nothjarnan/axiom#9]
Some inspiration can be found here: http://www.computercraft.info/forums2/index.php?/topic/17387-gitget-version-2-release/

**Comment by JasonTheKitten** [comment]
I am going to do this in the version that I am making.

However, I am also completely rewriting sys.axs to look nicer (as in readability and size on disk)
Btw, I'm replacing edge with EdgeX, but I will keep edge for compatibility reasons

**Comment by nothjarnan** [comment]
>  I'm replacing edge with EdgeX

I'd prefer if you don't use the Edge name, to avoid confusion, please.

**Comment by JasonTheKitten** [comment]
Ok
